name: Builds mac bundle only with prebuilt cljs
on:
  workflow_dispatch:

jobs:
  build-okp:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: macos
            # macos-latest is not used to ensure x86_64 works on old mac
            os: macos-12
            arch: x86_64
            target: x86_64-apple-darwin
          - build: macos
            os: macos-latest
            arch: aarch64
            target: aarch64-apple-darwin

    steps:
      - name: desktop repo
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
    
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Setup Node and yarn cache
        uses: actions/setup-node@v3
        with:
            node-version: 16
            cache: 'yarn'

      - name: Install node dependencies
        run:  yarn
        
      - name: Download 'artifacts-cljs-main-bundle' artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          #workflow: ${{ github.event.workflow_run.workflow_id }}
          ## Downloads the cljs built by the workflow 'build-cljs.yml' that was run successfully
          workflow: build-cljs.yml
          workflow_conclusion: success
          name: artifacts-cljs-main-bundle
          path: ./resources/public/cljs-out/dev

      - name: Set x86_64 botan env
        if: ${{ matrix.os == 'macos-latest' &&  matrix.arch == 'x86_64' }}
        run:  |
          echo "BOTAN_CONFIGURE_CC_ABI_FLAGS=-arch x86_64" >> $GITHUB_ENV
          echo "BOTAN_CONFIGURE_CPU=x86_64"  >> $GITHUB_ENV

      - name: Set aarch64 botan env
        if: ${{ matrix.os == 'macos-latest' &&  matrix.arch == 'aarch64' }} 
        run:  |
          echo "BOTAN_CONFIGURE_CC_ABI_FLAGS=-arch arm64" >> $GITHUB_ENV
          echo "BOTAN_CONFIGURE_CPU=arm64"  >> $GITHUB_ENV

      - run: |
          echo "BOTAN_CONFIGURE_CC_ABI_FLAGS=$BOTAN_CONFIGURE_CC_ABI_FLAGS"
          echo "BOTAN_CONFIGURE_CPU=$BOTAN_CONFIGURE_CPU"

      - name: App bundle
        run:  yarn tauri build --target ${{ matrix.target }}  
        env:
          BOTAN_CONFIGURE_OS: 'macos'
          BOTAN_CONFIGURE_CC: 'clang'
          BOTAN_CONFIGURE_DISABLE_MODULES: 'tls,pkcs11,sodium,filters'

          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}


      - name: Mac DMG final artifact 
        uses: actions/upload-artifact@v3
        # if: matrix.os == 'macos-latest'
        with:
          name: artifacts-mac-${{ matrix.arch }}
          path: ./src-tauri/target/${{ matrix.target }}/release/bundle/dmg/**.dmg

